-- 코드를 작성해주세요
SELECT it.ITEM_ID as 'ITEM_ID', it.ITEM_NAME as 'ITEM_NAME'
FROM ITEM_INFO as it
LEFT JOIN ITEM_TREE as tr ON it.ITEM_ID = tr.ITEM_ID
WHERE tr.PARENT_ITEM_ID is NULL
ORDER BY it.ITEM_ID asc;
