SELECT pr.PRODUCT_CODE, SUM(pr.PRICE * off.SALES_AMOUNT) as SALES
FROM PRODUCT as pr
JOIN OFFLINE_SALE as off ON pr.PRODUCT_ID = off.PRODUCT_ID
GROUP BY pr.PRODUCT_CODE
ORDER BY SALES desc, pr.PRODUCT_CODE asc;