-- 코드를 입력하세요
SELECT HI.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HI JOIN CAR_RENTAL_COMPANY_CAR CA ON HI.CAR_ID = CA.CAR_ID
WHERE MONTH(START_DATE) = 10 AND CA.CAR_TYPE = '세단'
GROUP BY HI.CAR_ID
ORDER BY HI.CAR_ID DESC;
