-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, hr.EMP_NO AS EMP_NO, em.EMP_NAME, em.POSITION, em.EMAIL
FROM HR_GRADE hr JOIN HR_EMPLOYEES em ON hr.EMP_NO = em.EMP_NO
GROUP BY hr.EMP_NO
ORDER BY SCORE desc
LIMIT 1;