-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', FI.BOARD_ID, '/', FI.FILE_ID, FI.FILE_NAME, FI.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE FI JOIN USED_GOODS_BOARD BO ON FI.BOARD_ID = BO.BOARD_ID
WHERE BO.VIEWS = (SELECT VIEWS FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1)
ORDER BY FI.FILE_ID DESC;
